Repository smartlyio/annotate-uncovered-lines-action, pull requests merged in 2022-08, with the labels that each got.

#2 allow glob in coverage file path to support monorepos
  .github/templates/release.yml.erb
  .github/workflows/check_release_label.yml
  .github/workflows/release.generated.yml
  README.md
  dist/covered.d.ts
  dist/index.js
  dist/index.js.map
  dist/licenses.txt
  package.json
  src/covered.ts
  src/index.ts
  yarn.lock
Labels: patch

#3 Update action to Node16
  .github/templates/release.yml.erb
  .github/workflows/release.generated.yml
  action.yml
Labels: patch

#4 Revert to node12 for executing the action
  .github/templates/release.yml.erb
  .github/workflows/release.generated.yml
  action.yml
Labels: minor

#5 Bring back Node16
  .github/templates/release.yml.erb
  .github/workflows/release.generated.yml
  action.yml
Labels: minor

#10 do not run over the list
  dist/index.js
  dist/index.js.map
  src/covered.ts
Labels: patch

#11 test coverage calculation more
  dist/index.js
  dist/index.js.map
  dist/src/covered.d.ts
  src/covered.ts
  src/index.ts
  test/test.spec.ts
Labels: patch

#9 lose .idea
  .gitignore
  .idea/.gitignore
  .idea/annotate-uncovered-lines-action.iml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/markdown.xml
  .idea/modules.xml
  .idea/vcs.xml
Labels: patch

#12 Move CI to ubuntu 20.04 from deprecated 18.04 runners
  .github/workflows/check_release_label.yml
Labels: no release
